image:
  repository: bitnami/postgresql
  tag: latest
  pullPolicy: IfNotPresent

postgresql:
  username: myuser
  password: mypassword
  database: coffee_db
  port: 5432

service:
  type: ClusterIP
  port: 5432

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

serviceAccount:
  create: true
  name: "my-service-account"
  
# resources: {}

# nodeSelector: {}

# tolerations: []

# affinity: {}
