apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coffee-api.fullname" . }}
  labels:
    {{- include "coffee-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "coffee-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "coffee-api.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "coffee-api.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port}}
        # resources:
        #   {{ toYaml .Values.resources | indent 10}}
        env:
        - name: DATABASE_URL
          value: "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@postgresql.svc.cluster.local:{{ .Values.postgresql.port }}/{{ .Values.postgresql.database }}"

