apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "coffee-api.fullname" . }}
  labels:
    {{- include "coffee-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "coffee-api.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "coffee-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
