name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - env/staging
  pull_request:
    branches:
      - main
      - env/staging

jobs:
  scan-secrets:
    name: Scan code for secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Scan code for secrets
      working-directory: ./CoffeeAPI
      uses: github/codeql-action/analyze@v2
      with:
        category: "Security"

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: scan-secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      working-directory: ./CoffeeAPI
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Packages
      working-directory: ./CoffeeAPI
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      working-directory: ./CoffeeAPI
      run: |
        docker build -t ghcr.io/${{ github.repository }}/coffee-api:${{ github.sha }} .

    - name: Push Docker image
      working-directory: ./CoffeeAPI
      run: |
        docker push ghcr.io/${{ github.repository }}/coffee-api:${{ github.sha }}

  test:
    name: Run Unit and Integration Tests
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      run: |
        pytest tests/unit

    - name: Run integration tests
      run: |
        pytest tests/integration

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Minikube
      uses: medyagh/setup-minikube@v2
      with:
        minikube-version: 'latest'
        kubernetes-version: 'latest'

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy PostgreSQL with Helm
      run: |
        helm upgrade --install postgresql ./HelmCharts/Postgresql \
          --set postgresql.database=${{ vars.POSTGRESQL_DATABASE }} \
          --set postgresql.username=${{ vars.POSTGRESQL_USERNAME }} \
          --set postgresql.password=${{ secrets.POSTGRESQL_PASSWORD }}

    - name: Deploy application with Helm
      run: |
        helm upgrade --install coffee-api ./HelmCharts/coffee-api \
          --set image.repository=ghcr.io/${{ github.repository }}/CoffeeService \
          --set image.tag=${{ github.sha }} \
          --set postgresql.database=${{ vars.POSTGRESQL_DATABASE }} \
          --set postgresql.username=${{ vars.POSTGRESQL_USERNAME }} \
          --set postgresql.password=${{ secrets.POSTGRESQL_PASSWORD }}

    - name: Check the service in Minikube
      run: |
        kubectl port-forward svc/coffee-api 8080:8080 &
        sleep 20
        curl -X POST http://localhost:8080/buy_coffee/ -d '{"payment_amount": 2.5}' -H "Content-Type: application/json"
