name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - env/staging
  pull_request:
    branches:
      - main
      - env/staging

jobs:
  scan-secrets:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./CoffeeAPI

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Scan code for secrets
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}


      #uses: github/codeql-action/analyze@v2
      #with:
       #category: "Security"

  build-and-push:
    defaults:
      run:
        working-directory: ./CoffeeAPI

    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: scan-secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}


    - name: Build Docker image
     
      run: |
        docker build -t ghcr.io/${{ github.repository  }}/coffee-api:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}/coffee-api:${{ github.sha }}

  # test:
  #   defaults:
  #     run:
  #       working-directory: ./CoffeeAPI
  #   name: Run Unit and Integration Tests
  #   runs-on: ubuntu-latest
  #   needs: build-and-push

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'

  #   - name: Install dependencies
  #     run: |
  #       pip install -r requirements.txt
  #       pip install pytest

  #   - name: Run unit tests
  #     run: |
  #       pytest tests/unit

  #   - name: Run integration tests
  #     run: |
  #       pytest tests/integration

  deploy:
    name: Deploy to Minikube
    runs-on: ubuntu-latest
   # needs: test

    steps:
      
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'
        kubernetes-version: 'latest'

    - name: Start Minikube
      run: |
        minikube start --driver=docker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy PostgreSQL with Helm
      run: |
        helm upgrade --install postgresql ./HelmCharts/Postgresql \
          --set postgresql.database=${{ vars.POSTGRESQL_DATABASE }} \
          --set postgresql.username=${{ vars.POSTGRESQL_USERNAME }} \
          --set postgresql.password=${{ secrets.POSTGRESQL_PASSWORD }}

    - name: Deploy application with Helm
      run: |
        helm upgrade --install coffee-api ./HelmCharts/CoffeeService \
          --set image.repository=ghcr.io/${{ github.repository }}/coffee-api \
          --set image.tag=${{ github.sha }} \
          --set postgresql.database=${{ vars.POSTGRESQL_DATABASE }} \
          --set postgresql.username=${{ vars.POSTGRESQL_USERNAME }} \
          --set postgresql.password=${{ secrets.POSTGRESQL_PASSWORD }}

    - name: Check the service in Minikube
      run: |
        sleep 70
        kubectl get svc

        kubectl get deployments

        kubectl describe pod coffee-api

        kubectl logs -p coffee-api
        kubectl port-forward svc/coffee-api 8000:8080 &
        sleep 20
        curl -X POST http://localhost:8000/buy_coffee/ -d '{"payment_amount": 2.5}' -H "Content-Type: application/json"
